# Generated by Django 3.2.12 on 2024-01-02 06:25

import BuildManager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuildManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildNum', models.IntegerField(default=BuildManager.models.Build.get_build_num, unique=True)),
                ('status', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('template', models.CharField(max_length=200)),
                ('problem_description', models.TextField()),
                ('other', models.TextField()),
                ('otherCost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currCPU', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu', to='BuildManager.part')),
                ('currCPUCooler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_cooler', to='BuildManager.part')),
                ('currCase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case', to='BuildManager.part')),
                ('currGPU', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpu', to='BuildManager.part')),
                ('currMemory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory', to='BuildManager.part')),
                ('currMotherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motherboard', to='BuildManager.part')),
                ('currOperatingSystem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_system', to='BuildManager.part')),
                ('currPowerSupply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_supply', to='BuildManager.part')),
                ('currStorage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage', to='BuildManager.part')),
            ],
        ),
    ]
