# Generated by Django 3.2.12 on 2024-01-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildManager', '0002_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='isTemplate',
            field=models.BooleanField(default=False),
        ),
    ]
