# Generated by Django 3.2.12 on 2024-01-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildManager', '0003_build_istemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
