# Generated by Django 3.2.12 on 2024-01-02 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuildManager', '0004_alter_build_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='isTemplate',
        ),
        migrations.AlterField(
            model_name='build',
            name='currCPU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu', to='BuildManager.part'),
        ),
        migrations.AlterField(
            model_name='build',
            name='currCPUCooler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_cooler', to='BuildManager.part'),
        ),
        migrations.AlterField(
            model_name='build',
            name='currCase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case', to='BuildManager.part'),
        ),
        migrations.AlterField(
            model_name='build',
            name='currGPU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpu', to='BuildManager.part'),
        ),
        migrations.AlterField(
            model_name='build',
            name='currMemory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory', to='BuildManager.part'),
        ),
        migrations.AlterField(
            model_name='build',
            name='currMotherboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motherboard', to='BuildManager.part'),
        ),
        migrations.AlterField(
            model_name='build',
            name='currOperatingSystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_system', to='BuildManager.part'),
        ),
        migrations.AlterField(
            model_name='build',
            name='currPowerSupply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_supply', to='BuildManager.part'),
        ),
        migrations.AlterField(
            model_name='build',
            name='currStorage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage', to='BuildManager.part'),
        ),
        migrations.AlterField(
            model_name='build',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='build',
            name='other',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='problem_description',
            field=models.TextField(blank=True),
        ),
    ]
